all: compile execute clean

compile:
	g++ xadrez\ 2.cpp -o prog Jogo.cpp FaseParque.cpp FaseBiblio.cpp Fase.cpp ListaEntidade.cpp GerenciadorColisao.cpp GerenciadoEventos.cpp GerenciadorGrafico.cpp Ente.cpp Entidade.cpp Personagem.cpp Jogador.cpp Menu.cpp Torre.cpp Rainha.cpp Inimigo.cpp Peao.cpp Obstaculo.cpp Tabuleiro.cpp -o sfml-app -lsfml-graphics -lsfml-window -lsfml-system

execute:
	./sfml-app
clean:
	clear
	
	
	
